kind: Deployment
apiVersion: extensions/v1beta1
metadata:
    name: example
spec:
    template:
          metadata:
            labels:
              app: example
          spec:
                  containers:
                          - name: web
                            image: openshift/deployment-example:v1
                            ports:
                            - containerPort: 8080

